In [2]:
import pandas as pd
import statistics as st
from scipy import stats # библиотека для расчетов
import plotly.express as px
import matplotlib.pyplot as plt # библиотека визуализации
from sklearn.metrics import matthews_corrcoef

df=pd.read_csv('model.csv')
#display(df.info())
df.head()

,Month,Year,Waist,Hips,Height,Weight,BMI,Waist/Hip
0,December,1953,24.000000,36.000000,65.000000,118.000000,19.630000,0.670000
1,January,1954,23.433172,34.698708,66.057258,114.936066,18.232168,0.677916
2,February,1954,23.433172,34.698708,66.057258,114.936066,18.232168,0.677916
3,March,1954,24.000000,35.000000,66.000000,118.000000,19.040000,0.690000
4,April,1954,23.433172,34.698708,66.057258,114.936066,18.232168,0.677916

In [3]:
df.corr()

C:\Users\lepni\AppData\Local\Temp\ipykernel_7224\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,Year,Waist,Hips,Height,Weight,BMI,Waist/Hip
Year,1.000000,0.292518,-0.281576,0.284482,-0.010753,0.025309,0.458945
Waist,0.292518,1.000000,0.283060,0.372637,0.452704,0.136549,0.742284
Hips,-0.281576,0.283060,1.000000,0.228054,0.541836,0.211395,-0.422412
Height,0.284482,0.372637,0.228054,1.000000,0.706569,-0.037934,0.198754
Weight,-0.010753,0.452704,0.541836,0.706569,1.000000,0.212701,0.067543
BMI,0.025309,0.136549,0.211395,-0.037934,0.212701,1.000000,-0.010173
Waist/Hip,0.458945,0.742284,-0.422412,0.198754,0.067543,-0.010173,1.000000

In [7]:
fig = px.imshow(df.corr(), text_auto=True)
fig.show()

C:\Users\lepni\AppData\Local\Temp\ipykernel_7224\2940540601.py:1: FutureWarning:

The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.

In [10]:
fig = px.scatter(df, "Waist/Hip", "Waist")
fig.show()

In [11]:
fig = px.scatter(df, "Weight", "Year")
fig.show()

In [14]:
fig = px.scatter_matrix(df)
fig.show()

In [15]:
temp=df[['Weight', 'Height']].copy()
round(temp.corr(),6)

          Weight    Height
Weight  1.000000  0.706569
Height  0.706569  1.000000

In [21]:
round(st.mean(df['Weight']),2)

114.94

In [20]:
round(st.mean(df['Height']),2)

66.06

In [24]:
fig = px.scatter(df, "Year", "Weight")
fig.show()